### ISSUE TITLE
Unable to run / install SAIGE.

### ISSUE THREAD

**Issue by drwhitehouse** [weizhouUMICH/SAIGE#104]
Hi, I've tried installing SAIGE using methods 1 & 2 here:

https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige

If I use method 1, then I get an error because SAIGE seems to be built against Boost 1.58. We only have 1.63 & 1.68 (and those are already out of date!).

If I use method 2, and try and build with the Boost libraries that we have (1.68 in the case below) I get the following error:

```
Installing package into ‘/data/home/aaw945/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘SAIGE’ ...
which: no cget in (/share/apps/centos7/cmake/gcc/4.8.5/3.12.2/bin:/share/apps/centos7/gcc/7.1.0/bin:/share/apps/centos7/R/gcc/4.8.5/3.5.3/bin:/share/apps/centos7/java/1.8.0_171/bin:/opt/sge/bin/lx-amd64:/usr/local/Modules/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/opt/puppetlabs/bin:/share/admin/bin:/share/admin/toolsbin:/data/home/aaw945/.local/bin:/data/home/aaw945/bin)
./configure: line 4: pip: command not found
cget must be installed to build SAIGE. Run .
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/data/home/aaw945/R/x86_64-pc-linux-gnu-library/3.5/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/749444.1.all.q/RtmpfXN0sg/file6ae7115c2bab/SAIGE_0.35.8.3.tar.gz’ had non-zero exit status
```

```
Currently Loaded Modulefiles:
 1) java/1.8.0_171-oracle(default)   2) R/3.5.3(default)   3) boost/1.68.0(default)   4) gcc/7.1.0(default)   5) cmake/3.12.2(default) 
``` 
Any help or suggestions would be appreciated.

**Comment by agilly** [comment]
The log seems to suggest that pip is not available. Do you have python+pip available as a module? This will then allow SAIGE to try and install cget. For me this failed, and I had to install cget manually (instructions can be found on their github page).

**Comment by drwhitehouse** [comment]
Even with python & pip available:

```
* installing *source* package ‘SAIGE’ ...
which: no cget in (/share/apps/centos7/python/3.6.3/bin:/share/apps/centos7/cmake/gcc/4.8.5/3.15.1/bin:/share/apps/centos7/gcc/7.1.0/bin:/share/apps/centos7/R/gcc/4.8.5/3.5.3/bin:/share/apps/centos7/java/1.8.0_171/bin:/opt/sge/bin/lx-amd64:/usr/local/Modules/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/opt/puppetlabs/bin:/share/admin/bin:/share/admin/toolsbin:/data/home/aaw945/.local/bin:/data/home/aaw945/bin)
Exception:
Traceback (most recent call last):
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/share/apps/centos7/python/3.6.3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/share/apps/centos7/python/3.6.3/lib/python3.6/site-packages/click-6.6.dist-info'
You are using pip version 9.0.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cget must be installed to build SAIGE. Run Collecting cget
Collecting click==6.6 (from cget)
  Using cached https://files.pythonhosted.org/packages/1c/7c/10b4132dd952b6a04e37626258825b8aa8c1eb99545f2eb26a77c21efb55/click-6.6-py2.py3-none-any.whl
Collecting six>=1.10 (from cget)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: click, six, cget.
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/data/home/aaw945/R/x86_64-pc-linux-gnu-library/3.5/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/752642.1.test.q/Rtmpl1UcZx/file55c23a2d5ba2/SAIGE_0.35.8.3.tar.gz’ had non-zero exit status
```

**Comment by agilly** [comment]
So pip seems to work but does not have rights to write where it wants to. You have several options, from running this in a virtualenv, to installing this as root, to manually installing cget using `pip install cget` The `--user` flag of pip will install it locally.

**Comment by drwhitehouse** [comment]
Think this is gonna have to be a Singularity container. Thanks for your help.
