### ISSUE TITLE
Errors trying to install Saige

### ISSUE THREAD

**Issue by dshifflett** [weizhouUMICH/SAIGE#113]
I am trying to load Saige on R version 3.6.0 but there are several errors when I run the  on packages saying that the package is not available for version 3.6.0 cget, Matrix and methods are three of the packages.  What version of R can the software be installed on?

**Comment by weizhouUMICH** [comment]
I've run SAIGE on R version 3.6.0 successfully.  Which R version have you used to compile to package?

**Comment by dshifflett** [comment]
Thanks for your response we have tried the items 1 through 3 from this link
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige and I have tried on 3.5.2 as well and I am not able to get the load completed the last error is on cget but I am not finding a package by that name.

**Comment by gpcr** [comment]
Same here : facing erors while installing :
```
Successfully installed xiaoyeli/superlu
Waf: The wscript in '/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen' is unreadable
Traceback (most recent call last):
Traceback (most recent call last):
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
Waf: The wscript in '/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/Rtmp72Fits/R.INSTALL4af5ce7b875/SAIGE-0.35.8.8/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
ERROR: configuration failed for package ‘SAIGE’

```

**Comment by wavefancy** [comment]
Hi @npatel22526  and @gpcr ,

Based on my recent experience, this is because of waf need python2.7. I switched from python3 to python2 to solve the problem. 

Check the issue I posted '[Please update the installation guide](https://github.com/weizhouUMICH/SAIGE/issues/118)' successfully installed SAIGE by conda from the scratch.  

Best regards
Wallace
