### ISSUE TITLE
wscript is unreadable. 

### ISSUE THREAD

**Issue by jameskozubek** [weizhouUMICH/SAIGE#209]
Hello, I am following your README, and running python3. 
However, i am getting this error. 

Extracting archive /tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/cget/cget/build/tmp-b1f61145cb374a6fac1288f1b7433142/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz ...
Can't find file cmake
Failed to build package statgen/savvy
Waf: The wscript in '/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
Waf: The wscript in '/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpfmvJJY/R.INSTALL380f66fc15ca/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/home/jim/miniconda3/envs/RSAIGE/lib/R/library/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp8178Te/file36fe4275babf/SAIGE_0.39.tar.gz’ had non-zero exit status

**Comment by jameskozubek** [comment]
I suspect this installation is not compatible with python3.

**Comment by jameskozubek** [comment]
I am using Python 3.7

**Comment by jameskozubek** [comment]
I solved this problem by downloading a new version of bgen on my own. 
 sudo hg clone https://gavinband@bitbucket.org/gavinband/bgen -u master
now works with python 3.7 and saige is downloaded.

**Comment by weizhouUMICH** [comment]
Hi @jameskozubek, 

Nice you have figured it out the problem. I will test the new bgen version as I removed several unused libraries from the bgen version in the SAIGE script. To avoid the conflicts of the python version and SAIGE, you may try use the conda env for installing and running SAIGE. 

Thanks,
Wei

**Comment by jameskozubek** [comment]
@weizhouUMICH I couldn't get it to work either in conda since it also got stalled on the wscript configuration which was calling for earlier versions of python and pip? However, once i download the new bgen, it worked fine with python3 and pip3. We are running SAIGE now, and so I will be excited to see the results.
