### ISSUE TITLE
SAIGE-GENE+ install

### ISSUE THREAD

**Issue by jingydz** [weizhouUMICH/SAIGE#428]
## Command
SAIGE]$ R CMD INSTALL  SAIGE
* installing to library ‘/home2/zhangjj/R/x86_64-conda-linux-gnu-library/4.1’
* installing *source* package ‘SAIGE’ ...
** using staged installation
Ignore package xz
。。。
-- Installing: /parastor300/work01/zhangjj/software/SAIGE/SAIGE/thirdParty/cget/cget/pkg/statgen__savvy/install/share/savvy/savvy-config-version.cmake
Successfully installed statgen/savvy
Downloading https://github.com/xiaoyeli/superlu/archive/b6177d0b743c0f1f6765db535dd8b6ce30c00061.tar.gz
  [----------------------------------------------------------------------]    0%
Unexpected error: <class 'urllib.error.URLError'>
<urlopen error http protocol error: bad status line>
Failed to build package xiaoyeli/superlu
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/home2/zhangjj/R/x86_64-conda-linux-gnu-library/4.1/SAIGE’

## Command
> devtools::install_github("weizhouUMICH/SAIGE")
Downloading GitHub repo weizhouUMICH/SAIGE@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
Enter one or more numbers, or an empty line to skip updates: 3
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpRGRf5u/remotes32497f06bb67/weizhouUMICH-SAIGE-a417272/DESCRIPTION’ ...
─  preparing ‘SAIGE’: (1.9s)
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking whether ‘INDEX’ is up-to-date ... NO
─  use ‘--force’ to remove the existing ‘INDEX’
─  excluding invalid files (918ms)
。。。
-- Installing: /parastor300/work01/zhangjj/software/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_zdefs.h
Successfully installed xiaoyeli/superlu
Waf: The wscript in '/parastor300/work01/zhangjj/software/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/parastor300/work01/zhangjj/software/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/parastor300/work01/zhangjj/software/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/parastor300/work01/zhangjj/software/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/parastor300/work01/zhangjj/software/SAIGE/thirdParty/bgen/wscript", line 33
        print "Creating %s build..." % bld.options.mode
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/home2/zhangjj/R/x86_64-conda-linux-gnu-library/4.1/SAIGE’

I have tried two installation methods to install SAIGE-GENE+, but the installation failed. Does anyone know why?

**Comment by jingydz** [comment]
extdata]$  Rscript step1_fitNULLGLMM.R     \
>         --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly_22chr  \
>         --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
>         --phenoCol=y_binary \
>         --covarColList=x1,x2,a9,a10 \
>         --qCovarColList=a9,a10  \
>         --sampleIDColinphenoFile=IID \
>         --traitType=binary        \
>         --outputPrefix=./output/example_binary \
>         --nThreads=24   \
>         --IsOverwriteVarianceRatioFile=TRUE
Loading required package: optparse
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /xxx/anaconda3/envs/RSAIGE/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] optparse_1.6.4 SAIGE_0.45.1

loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.5-4.1     Rcpp_1.0.1         getopt_1.20.3
[5] grid_3.6.1         RcppParallel_4.4.4 lattice_0.20-38
Error in parse_args(parser, positional_arguments = 0) :
  Error in getopt(spec = spec, opt = args) :
  long flag "qCovarColList" is invalid
Execution halted

**Comment by jingydz** [comment]
extdata]$ less cmd.sh 
extdata]$ Rscript step1_fitNULLGLMM.R     \
>         --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
>         --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
>         --phenoCol=y_binary \
>         --covarColList=x1,x2 \
>         --sampleIDColinphenoFile=IID \
>         --traitType=binary        \
>         --outputPrefix=./output/example_binary_includenonAutoforvarRatio \
>         --nThreads=4    \
>         --LOCO=FALSE    \
>         --minMAFforGRM=0.01
Loading required package: optparse
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /xxx/anaconda3/envs/RSAIGE/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] optparse_1.6.4 SAIGE_0.45.1

loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.5-4.1     Rcpp_1.0.1         getopt_1.20.3
[5] grid_3.6.1         RcppParallel_4.4.4 lattice_0.20-38
$plinkFile
[1] "./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly"

$phenoFile
[1] "./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt"

$phenoCol
[1] "y_binary"

$traitType
[1] "binary"

$invNormalize
[1] FALSE

$covarColList
[1] "x1,x2"

$sampleIDColinphenoFile
[1] "IID"

$tol
[1] 0.02

$maxiter
[1] 20

$tolPCG
[1] 1e-05

$maxiterPCG
[1] 500

$nThreads
[1] 4

$SPAcutoff
[1] 2

$numRandomMarkerforVarianceRatio
[1] 30

$skipModelFitting
[1] FALSE

$memoryChunk
[1] 2

$tauInit
[1] "0,0"

$LOCO
[1] FALSE

$traceCVcutoff
[1] 0.0025

$ratioCVcutoff
[1] 0.001

$outputPrefix
[1] "./output/example_binary_includenonAutoforvarRatio"

$IsOverwriteVarianceRatioFile
[1] FALSE

$IsSparseKin
[1] FALSE

$numRandomMarkerforSparseKin
[1] 2000

$isCateVarianceRatio
[1] FALSE

$relatednessCutoff
[1] 0.125

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$isCovariateTransform
[1] TRUE

$isDiagofKinSetAsOne
[1] FALSE

$useSparseSigmaConditionerforPCG
[1] FALSE

$useSparseSigmaforInitTau
[1] FALSE

$useSparseGRMtoFitNULL
[1] FALSE

$minMAFforGRM
[1] 0.01

$minCovariateCount
[1] -1

$includeNonautoMarkersforVarRatio
[1] FALSE

$FemaleOnly
[1] FALSE

$MaleOnly
[1] FALSE

$sexCol
[1] ""

$FemaleCode
[1] "1"

$MaleCode
[1] "0"

$noEstFixedEff
[1] FALSE

$help
[1] FALSE

tauInit  is  0 0
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5
Markers in the Plink file with MAF >=  0.01  will be used to construct GRM
4  threads are set to be used
Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  :
  WARNING: The variance ratio file ./output/example_binary_includenonAutoforvarRatio.varianceRatio.txt already exists. The new variance ratios will be output to ./output/example_binary_includenonAutoforvarRatio.varianceRatio.txt. In order to avoid overwriting the file, please remove the ./output/example_binary_includenonAutoforvarRatio.varianceRatio.txt or use the argument outputPrefix_varRatio to specify a different prefix to output the variance ratio(s). Otherwise, specify IsOverwriteVarianceRatioFile=TRUE so the file will be overwritten with new variance ratio(s)
Execution halted

**Comment by jingydz** [comment]
I have successfully installed the software.

$ R
> library(SAIGE)

**Comment by Naughtoncolin** [comment]
How did you solve your error?
