### ISSUE TITLE
Waf: The wscript in '/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen' is unreadable

### ISSUE THREAD

**Issue by kgerman73** [weizhouUMICH/SAIGE#89]
getting an error with devtools::install_github("weizhouUMICH/SAIGE")

...
kg/statgen__savvy/install/share/savvy/savvy-config.cmake
-- Installing: /tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/cget/cget/pkg/statgen__savvy/install/share/savvy/savvy-config-release.cmake
-- Installing: /tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/cget/cget/pkg/statgen__savvy/install/share/savvy/savvy-config-version.cmake
Successfully installed statgen/savvy
Waf: The wscript in '/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
Waf: The wscript in '/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmptfE1hI/R.INSTALLc3f27ab7f36/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/insight/app/R/v3.5.1/lib64/R/library/SAIGE’
* restoring previous ‘/insight/app/R/v3.5.1/lib64/R/library/SAIGE’
Error in i.p(...) :
  (converted from warning) installation of package ‘/tmp/RtmpuomSiz/filebc447d69894/SAIGE_0.35.8.1.tar.gz’ had non-zero exit status

# R --version
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

# gcc --version
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# cmake --version
cmake version 3.14.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by weizhouUMICH** [comment]
Hi, 

It seems if the issue is due the python version. Which python version is used? 

Thanks,
Wei

**Comment by kgerman73** [comment]
# python --version
Python 3.6.5

**Comment by weizhouUMICH** [comment]
By a quick google search, the error may be due to the python version?
https://github.com/cquery-project/cquery/issues/13
I used python 2.7 and python 3 as shown here https://github.com/weizhouUMICH/Docker/blob/master/SAIGE/Dockerfile

both worked...

**Comment by kgerman73** [comment]
I tried Python 2.7 but got a different error.  I was able to install the binary, just had to add this link since boost 1.58 is not available.

ln -s /usr/lib64/libboost_iostreams.so.1.53.0 /usr/lib64/libboost_iostreams.so.1.58.0

**Comment by weizhouUMICH** [comment]
That's good know. Thank you!

**Comment by weizhouUMICH** [comment]
Hi @kgerman73, since 0.36.1, the boost_iostreams is no longer needed. Thanks!

**Comment by hhx037** [comment]
Hi,

sorry to re-open this issue, but I'm running into the same problem with R 3.6.1 and the latest version of SAIGE, and switching to Python 2 does not help:

```
Python 3.6.3

Successfully installed xiaoyeli/superlu
Waf: The wscript in '/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
Waf: The wscript in '/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpBbyak3/R.INSTALLb24133ca2226/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Creating %s build..." % bld.options.mode)?
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/data/home/hhx037/R/x86_64-pc-linux-gnu-library/3.6/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpbBijWr/file4a131691efa9/SAIGE_0.36.3.2.tar.gz’ had non-zero exit status
```

```
Python 2.7.14

*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/home/hhx037/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so':
  /data/home/hhx037/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so: undefined symbol: sgecon_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/data/home/hhx037/R/x86_64-pc-linux-gnu-library/3.6/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp0OovaL/file8c0f4fb3e9aa/SAIGE_0.36.3.2.tar.gz’ had non-zero exit status

```

Any idea?

Kind regards,

Stephane
